<?php
function bookmarks_blocks_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
    //  $result = db_query("ALTER TABLE {bookmarks} ADD weight int");
      break;
    case 'pgsql':  
   //     $result = db_query("ALTER TABLE {bookmarks} ADD weight int");
      break;
  }  
}

function bookmarks_blocks_uninstall() {
 // $result = db_query("ALTER TABLE {bookmarks} DROP weight");
}

?>
