<?php
/********************************************************************
 * Drupal Hooks
 ********************************************************************/

/**
 * Implementation of hook_block().
 */
function bookmarks_blocks_block($op = "list", $delta = 0) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('User favorites');
    $blocks[1]['info'] = t('Add favorite');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch($delta) {
      case 0:
        return theme('bookmarks_blocks_favorites');
        break;
      case 1:
      	return theme('bookmarks_blocks_addBlock');
      	break;
    }
    return $block;
  }
}


/**
 * Implementation of hook_perm().
 */
function bookmarks_blocks_perm() {
  return array('access bookmarks_blocks');
}


/**
 * Implementation of hook_form_alter()
 */

/********************************************************************
 * Theme Hooks
 ********************************************************************/
 
 /**
 Returns an user's bookmarks block.

 @return array the paramter to pass to the block function.
**/

function theme_bookmarks_blocks_favorites() {

  global $user;

  // Do not let anonymous users have bookmarks, even if the admin decides this
  if ($user->uid != 0 && user_access('access bookmarks')) {

    $result = db_query('SELECT url, title FROM {bookmarks} WHERE uid = %d ORDER BY bmweight LIMIT 5', $user->uid);
    $bookmarks = array();
    $attributes['class'] = 'first';

	$path = $_SERVER['REQUEST_URI'];
  	$path = substr($path, (-strlen($str))+1);
  	if(strpos($path, 'bookmarks/') === 0) {
    	$attributes['class'] .= ' active';
    }
    
    $bookmarks[] = l('My favorite links', "bookmarks/$user->uid", $attributes);
    while ($data = db_fetch_object($result)) {
    	
    	//the mystery if - works but we dont kno why, logic seems reducable to a trivial if(n == n) case	
		$tempURL = $data->url;
		if(  $tempURL == drupal_get_path_alias(drupal_lookup_path('source', ($tempURL))) )
			$tempURL = drupal_lookup_path('source', ($tempURL));
		
//      $bookmarks[] = _bookmarks_get_link($data->url, $data->title);
		$bookmarks[] = _bookmarks_get_link($tempURL, $data->title);
    }

    // Print bookmarks list as an item list
    $output = (count($bookmarks) ? theme('item_list', $bookmarks) : t('You have no bookmarks.'));
    
    return array(
      'content' => $output
    );

  }

  // Not a logged in user or has no rights
  else {
    return FALSE;
  }
}

//added function to determine if a url is a bookmark
function bookmarks_blocks_isbookmark($curl) {
	global $user;
	
	//store all favorite urls in an array
	$result = db_query('SELECT url FROM {bookmarks} WHERE uid = %d', $user->uid);
	$urls = array();
	while ($data = db_fetch_object($result)) {
		$urls[] = $data->url;
	}
	
	//remove host name and protocol if present       foreach ($urls as $url) {	}
	
	$curalias = false;
	
	if($curl != drupal_get_path_alias($curl)) {
		$curlalias = drupal_get_path_alias($curl);
	}
	
	$boolean = false;
	
	foreach($urls as $url) {
		if($curl == $url || $curalias == $url)
			$boolean = true;
	}
	
	return $boolean;
}

function theme_bookmarks_blocks_addBlock() {
  	global $user;
  
  	$path = $_SERVER['REQUEST_URI'];
  	$path = substr($path, (-strlen($str))+1);
  
  	if(bookmarks_blocks_isbookmark($path)){
    	$output = '<div class="editfavorite">' 
    		. "<a href=\"/bookmarks/".$user->uid."/edit?url=".urlencode($path)."\"><span class=\"alt\">Add to favorites</span></a>"
    		. "</div>";
    
	    return array(
	    	'content' => $output
	    );  		
  	}
  
	else if ($user->uid != 0 && user_access('access bookmarks')) {
    
    	$output = '<div class="addfavorite">'
    		. "<a href=\"/bookmarks/$user->uid/add/quick\"><span class=\"alt\">Add to favorites</span></a>"
    		. "</div>";
    
	    return array(
	    	'content' => $output
	    );
	}

	else {
    	return FALSE;
  	}
}

?>