<?php
/*
 * Hook Menu
 */
function user_stats_display_menu() {

  $items = array();
  // Add a page to view stats for all users
  $items[] = array(
    'path' => 'admin/settings/userstats',
    'title' => t('User Stats'),
    'callback' => 'user_stats_display_userlist',
    'access' => user_access('administer user stats'),
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

function user_stats_display_admin_menu() {

  $items = array();
  // Add a page to view stats for all users
  $items[] = array(
    'path' => 'admin/settings/userstats',
    'title' => t('User Stats'),
    'callback' => 'user_stats_display_userlist',
    'access' => user_access('administer user stats'),
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

/*
 * Display a stats page of all users
 */
function user_stats_display_userlist() {
  $output = drupal_get_form('user_stats_display_admin_userlist');
  return $output;

}



function user_stats_display_admin_userlist() {
  $filter = user_build_filter_query();

  $header = array(
    array('data' => t('Username'), 'field' => 'u.name'),
    t('Roles'),
    array('data' => t('First access'), 'field' => 'u.created'),
    array('data' => t('Last access'), 'field' => 'u.access'),
    array('data' => t('Login count'), 'field' => 'CAST(v.value AS DECIMAL)'),
//    t('Login Count'),
    t('Operations')
  );

//  $sql = 'SELECT DISTINCT u.uid, u.name, u.created, u.access FROM {users} u LEFT JOIN {users_roles} ur ON u.uid = ur.uid '. $filter['join'] .' WHERE u.uid != 0 '. $filter['where'];
  $sql = 'select f.title, CAST(v.value AS DECIMAL), u.uid, u.name, u.created, u.access from profile_fields as f inner join profile_values as v on v.fid = f.fid and f.fid = 3 right join users as u on u.uid = v.uid' . $filder['join'] . $filter['where'];
  $sql .= tablesort_sql($header);
  $result = pager_query($sql, 2000, 0, NULL, $filter['args']);

  foreach (module_invoke_all('user_operations') as $operation => $array) {
    $options[$operation] = $array['label'];
  }
  $form['options']['operation'] = array(
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => 'unblock',
  );
  $form['options']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update'),
  );

  $destination = drupal_get_destination();

  $status = array(t('blocked'), t('active'));
  $roles = user_roles(1);

  while ($account = db_fetch_object($result)) {
	$display_account = user_stats_user_load($account->uid);
    $accounts[$account->uid] = '';
    $form['name'][$account->uid] = array('#value' => theme('username', $account));
    $users_roles = array();
    $roles_result = db_query('SELECT rid FROM {users_roles} WHERE uid = %d', $account->uid);
    while ($user_role = db_fetch_object($roles_result)) {
      $users_roles[] = $roles[$user_role->rid];
    }
    asort($users_roles);
    $form['roles'][$account->uid][0] = array('#value' => theme('item_list', $users_roles));
    $form['first_access'][$account->uid] =  array('#value' => date("m/d/Y", $account->created));
    $form['last_access'][$account->uid] =  array('#value' => $account->access ? date("m/d/Y", $account->access) : t('never'));
    $form['login_count'][$account->uid] =  array('#value' => $display_account->user_login_count ? $display_account->user_login_count : 0);
    $form['operations'][$account->uid] = array('#value' => l(t('edit'), "user/$account->uid/edit", array(), $destination));
  }
  $form['accounts'] = array(
    '#type' => 'checkboxes',
    '#options' => $accounts
  );
  $form['pager'] = array('#value' => theme('pager', NULL, 2000, 0));

  return $form;
}

/**
 * Theme user administration overview.
 */
function theme_user_stats_display_admin_userlist($form) {
  // Overview table:
  $header = array(
    array('data' => t('Username'), 'field' => 'u.name'),
    t('Roles'),
    array('data' => t('First access'), 'field' => 'u.created'),
    array('data' => t('Last access'), 'field' => 'u.access'),
	array('data' => t('Login count'), 'field' => 'CAST(v.value AS DECIMAL)'),
//    t('Login count'),
    t('Operations')
  );

  if (isset($form['name']) && is_array($form['name'])) {
    foreach (element_children($form['name']) as $key) {
      $rows[] = array(
        drupal_render($form['name'][$key]),
        drupal_render($form['roles'][$key]),
        drupal_render($form['first_access'][$key]),
        drupal_render($form['last_access'][$key]),
        drupal_render($form['login_count'][$key]),
        drupal_render($form['operations'][$key]),
      );
    }
  }
  else  {
    $rows[] = array(array('data' => t('No users available.'), 'colspan' => '7'));
  }

  $output .= theme('table', $header, $rows);
  if ($form['pager']['#value']) {
    $output .= drupal_render($form['pager']);
  }

  return $output;
}

?>